### ISSUE TITLE
Remove hard dependency on git during build

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/ASF-ui#152]
`git` should not be required during build, and ASF-ui can't assume that it's part of the git repo. User is free to download zip archive with source code and compile without support for git, which right now is not possible:

```
Command failed: git rev-parse HEAD
fatal: Not a git repository: /src/bjcxyv9fdebyrj7ka5zfelp/.git/modules/ASF-ui

    at checkExecSyncError (child_process.js:618:11)
    at execSync (child_process.js:655:13)
    at module.exports (/app/node_modules/git-revision-webpack-plugin/lib/helpers/run-git-command.js:25:34)
    at GitRevisionPlugin.commithash (/app/node_modules/git-revision-webpack-plugin/lib/index.js:58:10)
    at module.exports (/app/webpack.config.js:82:50)
    at handleFunction (/app/node_modules/webpack-cli/bin/prepareOptions.js:23:13)
    at prepareOptions (/app/node_modules/webpack-cli/bin/prepareOptions.js:9:5)
    at requireConfig (/app/node_modules/webpack-cli/bin/convert-argv.js:136:14)
    at /app/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/app/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/app/node_modules/webpack-cli/bin/cli.js:241:39)
    at Object.parse (/app/node_modules/yargs/yargs.js:563:18)
    at /app/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/app/node_modules/webpack-cli/bin/cli.js:530:3)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
```

I believe this happens because of https://github.com/JustArchiNET/ASF-ui/commit/ae17aaac0c26fa7878f7b72140fae9f9a60b2991 - thanks!

**Comment by JustArchi** [comment]
The best possible fallback idea that I have right now is taking the most recent `LastModified` time out of all source files, this could be used as a decent way to define exact commit hash. Date of the build is sadly not sufficient as user could build outdated source tree at any point of time.

This is still prone to having forks and manually modifying source files, but it should be good enough for majority of cases. Alternatively, you can always decide that such no-git builds simply will not have versioning info, which is also valid.

**Comment by JustArchi** [comment]
Using ASF version should be good enough, as ASF version is available always, and you can always check exact ASF-ui commit hash based on which one was included in given ASF version.

**Comment by JustArchi** [comment]
Of course this will be still prone to a custom ASF-ui build with expected ASF version, but I don't expect a lot of people to have ASF-ui builds that do not match ASF version they're using.

**Comment by Aareksio** [comment]
> Using ASF version should be good enough, as ASF version is available always, and you can always check exact ASF-ui commit hash based on which one was included in given ASF version.

I don't think it benefits us at all. The user is _not_ using bundle that came with ASF in such scenario. ASF version will be additionally included in error report anyway.

> Of course this will be still prone to a custom ASF-ui build with expected ASF version, but I don't expect a lot of people to have ASF-ui builds that do not match ASF version they're using.

In such case we'll get `version: no-git; asf-version: x.x.x.x`. Remember we do not have access to ASF at build time - we can fetch the version only after the user connected to ASF API.
