### ISSUE TITLE
Unable to reset BGR key file

### ISSUE THREAD

**Issue by diamond-gold** [JustArchiNET/ASF-ui#1552]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest stable release

### ASF-ui version

156992e

### Bug description

Tried reset key file but nothing happens, no error in log

### Expected behavior

Key file gets reset

### Actual behavior

Key file not reset

### Steps to reproduce

1. Click on bot on bots page
2. Click BGR
3. Click Reset
4. Click Reset

### Possible reason/solution

Manual deletion of key file

### Can you help us with this bug report?

Somehow, I can test and offer feedback, but can't code

**Comment by Abrynos** [comment]
> no error in log

Which log are you referring to? ASFs log in the `log.txt` file or your browsers console (you can access this one by pressing the F12 key on the web page)

**Comment by diamond-gold** [comment]
I am referring to ASF log

**Comment by Abrynos** [comment]
Can you please check the browser log as well?

**Comment by diamond-gold** [comment]
The browser log show this
`main.44c3b65.bundle.js:2          DELETE https://xxx/api/bot/xxx/gamesToRedeemInBackground 403
(anonymous) @ main.44c3b65.bundle.js:2
t.exports @ main.44c3b65.bundle.js:2
t.exports @ main.44c3b65.bundle.js:2
Promise.then (async)
l.request @ main.44c3b65.bundle.js:2
r.forEach.l.<computed> @ main.44c3b65.bundle.js:2
(anonymous) @ main.44c3b65.bundle.js:2
m @ main.44c3b65.bundle.js:2
onReset @ 8848.e54b5a0.chunk.js:1
Bt @ main.44c3b65.bundle.js:2
n @ main.44c3b65.bundle.js:2
Bt @ main.44c3b65.bundle.js:2
t.$emit @ main.44c3b65.bundle.js:2
click @ 8848.e54b5a0.chunk.js:1
Bt @ main.44c3b65.bundle.js:2
n @ main.44c3b65.bundle.js:2
i._wrapper @ main.44c3b65.bundle.js:2
main.44c3b65.bundle.js:2 Error: HTTP Error 403
    at u (main.44c3b65.bundle.js:2:20282)
    at f (main.44c3b65.bundle.js:2:20484)
    at async a.onReset (8848.e54b5a0.chunk.js:1:13946)
Wt @ main.44c3b65.bundle.js:2
Vt @ main.44c3b65.bundle.js:2
Ut @ main.44c3b65.bundle.js:2
(anonymous) @ main.44c3b65.bundle.js:2
Promise.catch (async)
Bt @ main.44c3b65.bundle.js:2
n @ main.44c3b65.bundle.js:2
Bt @ main.44c3b65.bundle.js:2
t.$emit @ main.44c3b65.bundle.js:2
click @ 8848.e54b5a0.chunk.js:1
Bt @ main.44c3b65.bundle.js:2
n @ main.44c3b65.bundle.js:2
i._wrapper @ main.44c3b65.bundle.js:2`

**Comment by diamond-gold** [comment]
I have found the culprit, `limit_except GET POST { deny all; }` is specified in nginx config and that is forbidding the DELETE operation. Works fine after removing that line.
