### ISSUE TITLE
IPC doesn't work

### ISSUE THREAD

**Issue by iliketrainsornot** [JustArchiNET/ASF-ui#1620]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest stable release

### ASF-ui version

c457dc3

### Bug description

tried opening asf and it said "IPC STARTED" but it said address binded

### Expected behavior

asf ui opening

### Actual behavior

simply asf UI

### Can you help us with this bug report?

No, I don't have time, skills or willings for any of that

### Global ASF.json config file

```json
{
  "IPCPassword": "REDACTED",
  "SteamOwnerID": REDACTED,
  "SteamTokenDumperPluginEnabled": true
}
```

### BotName.json config of all affected bot instances

```json
it's not the bots
```

**Comment by iliketrainsornot** [comment]
2022-12-24 12:21:35|ArchiSteamFarm-13188|INFO|ASF|InitCore() ArchiSteamFarm V5.4.0.3 (win-x64/8302d2cc-4264-482a-8f56-30e2dadaef9b | .NET 7.0.0; win10-x64; Microsoft Windows 10.0.19045)
2022-12-24 12:21:35|ArchiSteamFarm-13188|INFO|ASF|InitCore() Copyright © 2015-2022 JustArchiNET
2022-12-24 12:21:35|ArchiSteamFarm-13188|WARN|ASF|InitCore() You're attempting to run ASF as the administrator (root). This causes a significant security risk to your machine, and as ASF does not require root access for its operation, we recommend to run it as non-administrator user if possible.
2022-12-24 12:21:44|ArchiSteamFarm-13188|INFO|ASF|InitPlugins() Initializing Plugins...
2022-12-24 12:21:44|ArchiSteamFarm-13188|INFO|ASF|InitPlugins() Loading ASFFreeGamesPlugin V1.2.9.0...
2022-12-24 12:21:44|ArchiSteamFarm-13188|INFO|ASF|InitPlugins() ASFFreeGamesPlugin has been loaded successfully!
2022-12-24 12:21:44|ArchiSteamFarm-13188|INFO|ASF|InitPlugins() Loading SteamTokenDumperPlugin V5.4.0.3...
2022-12-24 12:21:44|ArchiSteamFarm-13188|INFO|ASF|InitPlugins() SteamTokenDumperPlugin has been loaded successfully!
2022-12-24 12:21:44|ArchiSteamFarm-13188|INFO|ASF|InitPlugins() You've loaded one or multiple custom plugins into ASF. Since we're unable to offer support for modded setups, please contact the appropriate developers of the plugins that you decided to use in case of any issues.
2022-12-24 12:21:44|ArchiSteamFarm-13188|INFO|ASF|UpdateAndRestart() ASF will automatically check for new versions every 1 day.
2022-12-24 12:21:44|ArchiSteamFarm-13188|INFO|ASF|Update() Cleaning up old files after update...
2022-12-24 12:21:49|ArchiSteamFarm-13188|ERROR|ASF|Update() System.IO.IOException: Access to the path '\\?\C:\Users\\Desktop\Stuff for games n shit\ASF-win-x64\_old\www\images' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at System.IO.Directory.Delete(String, Boolean)
   at ArchiSteamFarm.Core.ASF.Update(Boolean updateOverride)
2022-12-24 12:21:49|ArchiSteamFarm-13188|INFO|ASF|Load() Loading STD global cache...
2022-12-24 12:21:49|ArchiSteamFarm-13188|INFO|ASF|Load() Validating STD global cache integrity...
2022-12-24 12:21:49|ArchiSteamFarm-13188|INFO|ASF|OnASFInit() SteamTokenDumperPlugin has been initialized successfully, thank you in advance for your help. The first submission will happen in approximately 14 minutes from now.
2022-12-24 12:21:49|ArchiSteamFarm-13188|INFO|ASF|StartInteractiveConsole() Interactive console is now active, type 'c' in order to enter command mode.
2022-12-24 12:21:49|ArchiSteamFarm-13188|INFO|ASF|Start() Starting IPC server...
2022-12-24 12:21:50|ArchiSteamFarm-13188|ERROR|ASF|Start() System.IO.IOException: Failed to bind to address http://localhost:1242.
 ---> System.AggregateException: One or more errors occurred. (An attempt was made to access a socket in a way forbidden by its access permissions.) (An attempt was made to access a socket in a way forbidden by its access permissions.)
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError, Boolean , String )
   at System.Net.Sockets.Socket.DoBind(EndPoint, SocketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint, CancellationToken )
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint, ConnectionDelegate, EndpointConfig , CancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions, AddressBindContext, CancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext, CancellationToken)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError, Boolean , String )
   at System.Net.Sockets.Socket.DoBind(EndPoint, SocketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint, CancellationToken )
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint, ConnectionDelegate, EndpointConfig , CancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions, AddressBindContext, CancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext, CancellationToken)<---

   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext, CancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext, CancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1, AddressBindContext, CancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1, CancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken )
   at ArchiSteamFarm.IPC.ArchiKestrel.Start()

**Comment by MrBurrBurr** [comment]
This is ASF problem, not ASF-ui problem.
